# TreeCapitation999 Configuration File

# Whether to break leaves when breaking trees
break-leaves: true

# Whether to require an axe to use treecapitation
require-axe: true

# Whether to drop all logs as one stack
drop-as-one: true

# Whether to automatically replant saplings
auto-replant: true

# Maximum number of blocks that can be broken in a single treecapitation
max-tree-blocks: 120

# Maximum distance to search for connected logs (in blocks)
max-break-distance: 50

# Radius to search for leaves around logs (in blocks)
leaf-search-radius: 5

# Custom logs from other plugins/modpacks (add material names here)
custom-logs:
#  - "MY_CUSTOM_LOG"
#  - "ANCIENT_LOG"

# Permission Settings
permissions:
  # Base permission to use the plugin
  use: "treecapitation.use"
  # Permission to bypass cooldowns
  bypass-cooldown: "treecapitation.bypass.cooldown"
  # Permission for instant breaking
  instant-break: "treecapitation.instant"